### PR TITLE
Validate the system tags

### LINKED ISSUE #11: Save without a tag specified causes weird error message
While testing #10 I tried to save a rule without specify a tag and got following:

bildschirmfoto 2016-08-19 um 14 51 26

Part of the essential output:

```
<h2><strong>Technische Details</strong></h2> <ul> <li>Entfernte Adresse: ::1</li> <li>Anfragekennung: K2cbjCKQyXwB2Bztl7Hs</li> <li>Typ: InvalidArgumentException</li> <li>Code: 0</li> <li>Nachricht: Tag id must be integer</li> <li>Datei: /Users/morrisjobke/Projects/nextcloud/server/lib/private/SystemTag/SystemTagManager.php</li> <li>Zeile: 99</li> </ul> <br /> <h2><strong>Ablauf</strong></h2> <pre>#0 /Users/morrisjobke/Projects/nextcloud/server/apps/files_automatedtagging/lib/Operation.php(83): OC\SystemTag\SystemTagManager-&gt;getTagsByIds(Array) #1 /Users/morrisjobke/Projects/nextcloud/server/apps/workflowengine/lib/Manager.php(260): OCA\FilesAutomatedTagging\Operation-&gt;validateOperation(&#039;ewrwer&#039;, Array, &#039;&#039;) #2 /Users/morrisjobke/Projects/nextcloud/server/apps/workflowengine/lib/Manager.php(180): OCA\WorkflowEngine\Manager-&gt;validateOperation(&#039;OCA\\FilesAutoma...&#039;, &#039;ewrwer&#039;, Array, &#039;&#039;) #3 /Users/morrisjobke/Projects/nextcloud/server/apps/workflowengine/lib/Controller/FlowOperations.php(69): OCA\WorkflowEngine\Manager-&gt;addOperation(&#039;OCA\\FilesAutoma...&#039;, &#039;ewrwer&#039;, Array, &#039;&#039;) #4 [internal function]: OCA\WorkflowEngine\Controller\FlowOperations-&gt;addOperation(&#039;OCA\\FilesAutoma...&#039;, &#039;ewrwer&#039;, Array, &#039;&#039;) #5 /Users/morrisjobke/Projects/nextcloud/server/lib/private/AppFramework/Http/Dispatcher.php(160): call_user_func_array(Array, Array) #6 /Users/morrisjobke/Projects/nextcloud/server/lib/private/AppFramework/Http/Dispatcher.php(90): OC\AppFramework\Http\Dispatcher-&gt;executeController(Object(OCA\WorkflowEngine\Controller\FlowOperations), &#039;addOperation&#039;) #7 /Users/morrisjobke/Projects/nextcloud/server/lib/private/AppFramework/App.php(117): OC\AppFramework\Http\Dispatcher-&gt;dispatch(Object(OCA\WorkflowEngine\Controller\FlowOperations), &#039;addOperation&#039;) #8 /Users/morrisjobke/Projects/nextcloud/server/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main(&#039;FlowOperationsC...&#039;, &#039;addOperation&#039;, Object(OC\AppFramework\DependencyInjection\DIContainer), Array) #9 [internal function]: OC\AppFramework\Routing\RouteActionHandler-&gt;__invoke(Array) #10 /Users/morrisjobke/Projects/nextcloud/server/lib/private/Route/Router.php(298): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array) #11 /Users/morrisjobke/Projects/nextcloud/server/lib/base.php(969): OC\Route\Router-&gt;match(&#039;/apps/workflowe...&#039;) #12 /Users/morrisjobke/Projects/nextcloud/server/index.php(48): OC::handleRequest() #13 {main}</pre> </span> <div class="push"></div><!-- for sticky footer --> </div> </div> <footer role="contentinfo"> <p class="info"> <a href="https://nextcloud.com" target="_blank" rel="noreferrer">Nextcloud</a> – ein sicherer Ort für all Ihre Daten	</p> </footer> </body> </html>
```

@nickvergessen Could you check that?

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #11

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by nickvergessen** [comment]
Now fixes #11

**Comment by MorrisJobke** [comment]
```
PHP Fatal error:  Interface 'OCP\WorkflowEngine\IOperation' not found in /home/travis/build/nextcloud/server/apps/files_automatedtagging/lib/Operation.php on line 33
PHP Stack trace:
PHP   1. {main}() /home/travis/.phpenv/versions/5.4.37/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/travis/.phpenv/versions/5.4.37/bin/phpunit:722
PHP   3. PHPUnit_TextUI_Command->run() phar:///home/travis/.phpenv/versions/5.4.37/bin/phpunit/phpunit/TextUI/Command.php:104
PHP   4. PHPUnit_TextUI_Command->handleArguments() phar:///home/travis/.phpenv/versions/5.4.37/bin/phpunit/phpunit/TextUI/Command.php:114
PHP   5. PHPUnit_Util_Configuration->getTestSuiteConfiguration() phar:///home/travis/.phpenv/versions/5.4.37/bin/phpunit/phpunit/TextUI/Command.php:664
PHP   6. PHPUnit_Util_Configuration->getTestSuite() phar:///home/travis/.phpenv/versions/5.4.37/bin/phpunit/phpunit/Util/Configuration.php:814
PHP   7. PHPUnit_Framework_TestSuite->addTestFiles() phar:///home/travis/.phpenv/versions/5.4.37/bin/phpunit/phpunit/Util/Configuration.php:901
PHP   8. PHPUnit_Framework_TestSuite->addTestFile() phar:///home/travis/.phpenv/versions/5.4.37/bin/phpunit/phpunit/Framework/TestSuite.php:400
PHP   9. PHPUnit_Framework_TestSuite->addTestSuite() phar:///home/travis/.phpenv/versions/5.4.37/bin/phpunit/phpunit/Framework/TestSuite.php:374
PHP  10. PHPUnit_Framework_TestSuite->__construct() phar:///home/travis/.phpenv/versions/5.4.37/bin/phpunit/phpunit/Framework/TestSuite.php:289
PHP  11. PHPUnit_Framework_TestSuite->addTestMethod() phar:///home/travis/.phpenv/versions/5.4.37/bin/phpunit/phpunit/Framework/TestSuite.php:188
PHP  12. PHPUnit_Framework_TestSuite::createTest() phar:///home/travis/.phpenv/versions/5.4.37/bin/phpunit/phpunit/Framework/TestSuite.php:842
PHP  13. PHPUnit_Util_Test::getProvidedData() phar:///home/travis/.phpenv/versions/5.4.37/bin/phpunit/phpunit/Framework/TestSuite.php:465
PHP  14. ReflectionMethod->invoke() phar:///home/travis/.phpenv/versions/5.4.37/bin/phpunit/phpunit/Util/Test.php:392
PHP  15. OCA\FilesAutomatedTagging\Tests\StorageWrapperTest->dataGetCache() phar:///home/travis/.phpenv/versions/5.4.37/bin/phpunit/phpunit/Util/Test.php:392
PHP  16. OCA\FilesAutomatedTagging\Tests\StorageWrapperTest->getOperationMock() /home/travis/build/nextcloud/server/apps/files_automatedtagging/tests/StorageWrapperTest.php:42
PHP  17. PHPUnit_Framework_MockObject_MockBuilder->getMock() /home/travis/build/nextcloud/server/apps/files_automatedtagging/tests/StorageWrapperTest.php:37
PHP  18. PHPUnit_Framework_TestCase->getMock() phar:///home/travis/.phpenv/versions/5.4.37/bin/phpunit/phpunit-mock-objects/Framework/MockObject/MockBuilder.php:142
PHP  19. PHPUnit_Framework_MockObject_Generator->getMock() phar:///home/travis/.phpenv/versions/5.4.37/bin/phpunit/phpunit/Framework/TestCase.php:1256
PHP  20. PHPUnit_Framework_MockObject_Generator->generate() phar:///home/travis/.phpenv/versions/5.4.37/bin/phpunit/phpunit-mock-objects/Framework/MockObject/Generator.php:255
PHP  21. PHPUnit_Framework_MockObject_Generator->generateMock() phar:///home/travis/.phpenv/versions/5.4.37/bin/phpunit/phpunit-mock-objects/Framework/MockObject/Generator.php:557
PHP  22. class_exists() phar:///home/travis/.phpenv/versions/5.4.37/bin/phpunit/phpunit-mock-objects/Framework/MockObject/Generator.php:719
PHP  23. Composer\Autoload\ClassLoader->loadClass() phar:///home/travis/.phpenv/versions/5.4.37/bin/phpunit/phpunit-mock-objects/Framework/MockObject/Generator.php:719
PHP  24. Composer\Autoload\includeFile() /home/travis/build/nextcloud/server/lib/composer/composer/ClassLoader.php:301
PHP  25. include() /home/travis/build/nextcloud/server/lib/composer/composer/ClassLoader.php:412
```

**Comment by nickvergessen** [comment]
Yeah needs the core branch merged

**Comment by MorrisJobke** [comment]
> Yeah needs the core branch merged

Ah right -.-

**Comment by LukasReschke** [comment]
Retriggered tests.

**Pull request merged**
