### PR TITLE
Move the admin settings to the workflow section

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] nextcloud/server#995

@blizzz

### CODE REVIEW

**Comment by blizzz** [comment]
test fails:

```
.....PHP Fatal error:  Class 'OCA\FilesAutomatedTagging\Controller\AdminController' not found in /home/travis/build/nextcloud/server/apps/files_automatedtagging/tests/Controller/AdminControllerTest.php on line 48
```

**Comment by nickvergessen** [comment]
Jup, updated

**Comment by blizzz** [comment]
:+1: tested, works

**Comment by blizzz** [comment]
server PR was merged

**Pull request merged**
